MAIN:
  cdf_defaultlabel: CDF
  figure_plotperrow: 1
  figure_sharexaxis: false
  figure_shareyaxis: false
  figure_singlecolumnnarrowplot: true
  figure_singlecolumnnarrowplot_xtitlelocation: 0.3
  figure_title: \\textbf{'Test Title'}
  figure_xlabelfrominputfile: true
  figure_ylabelfrominputfile: true
  figure_zlabelfrominputfile: false
  figurelegend: false
  figurelegend_bbox_to_anchor: null
  figurelegend_border_axispad: 0.0
  figurelegend_location: 2
  figurelegend_mode: null
  figurelegend_ncolumn: 1
  histogram_defaultlabel: Density
  inputfile_delimeter: ','
  inputfile_directory: inputFiles
  inputfile_encoder: utf-8-sig
  inputfile_format: csv
  inputfile_name: plotFromCsv
  outputfigure_directory: outputFiles
  outputfigure_format: pdf
  outputfigure_xdimension: 25.6
  outputfigure_ydimension: 14.4
PLOT:
  Subplot0:
    dataset0:
      graph_alpha: 0.5
      graph_type: snsline
      input_edata: 0
      input_xdata: 4
      input_ydata: 3
      input_zdata: 5
      plot_legend: megend
      dataset_ylabel: xyxzs
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25
    dataset1:
      graph_alpha: 0.5
      graph_type: snsline
      input_edata: 0
      input_xdata: 3
      input_ydata: 4
      input_zdata: 5
      plot_legend: megend2
      dataset_ylabel: yy
      yaxis_axisoffset: 0.1
      yaxis_on: false
      yaxis_ylimthreshold: 25
    dataset2:
      graph_alpha: 0.5
      graph_type: snsline
      input_edata: 0
      input_xdata: 7
      input_ydata: 8
      input_zdata: 5
      plot_legend: megend3
      dataset_ylabel: z
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25

    multipleyaxis: true
    plot_threed_azimdegree: -160
    plot_threed_elevdegree: 30
    plot_title: subplot1
    plot_xlabel: x
    plot_xlabel_pad: 2.0
    plot_xlimit_max: null
    plot_xlimit_min: null
    plot_xscale: linear
    plot_xticks_distance: null
    plot_xticks_max: null
    plot_xticks_min: null
    plot_ylabel: yi
    plot_ylabel_pad: 2.0
    plot_ylimit_max: null
    plot_ylimit_min: null
    plot_yscale: linear
    plot_yticks_distance: null
    plot_yticks_max: null
    plot_yticks_min: null
    plot_zlabel: z
    plot_zlabel_pad: 2.0
    plot_zlimit_max: null
    plot_zlimit_min: null
    plot_zscale: linear
    plot_zticks_distance: null
    plot_zticks_max: null
    plot_zticks_min: null
    plotlegend: true
    plotlegend_bbox_to_anchor: null
    plotlegend_border_axisPad: 0.0
    plotlegend_location: 2
    plotlegend_mode: null
    plotlegend_ncolumn: 1
