MAIN:
  cdf_defaultlabel: CDF
  figure_plotperrow: 3
  figure_sharexaxis: false
  figure_shareyaxis: false
  figure_singlecolumnnarrowplot: true
  figure_singlecolumnnarrowplot_xtitlelocation: 0.3
  figure_title: ''
  figure_xlabelfrominputfile: true
  figure_ylabelfrominputfile: true
  figure_zlabelfrominputfile: false
  figurelegend: false
  figurelegend_bbox_to_anchor_x: 0.35
  figurelegend_bbox_to_anchor_y: 0.12
  figurelegend_border_axispad: 0.0
  figurelegend_location: 2
  figurelegend_mode: null
  figurelegend_ncolumn : 1
  figure_show : false
  histogram_defaultlabel: Density
  inputfile_delimeter: ','
  inputfile_directory: inputFiles
  inputfile_encoder: utf-8-sig
  inputfile_format: csv
  inputfile_name: input
  outputfigure_directory: outputFiles
  outputfigure_format: pdf
  outputfigure_xdimension: 25.6
  outputfigure_ydimension: 14.4

PLOT:
  Subplot0:
    dataset0:
      graph_alpha: 0.65
      graph_type: histogram
      input_edata: 0
      input_xdata: 30
      input_ydata: 2
      input_zdata: 
      plot_legend: DJI Spark - Captured Data
      dataset_ylabel: Data Rate (kbps)
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25

    multipleyaxis: false
    plot_threed_azimdegree: -160
    plot_threed_elevdegree: 30
    plot_title: 
    plot_xlabel: Data Rate (kbps)
    plot_xlabel_pad: 2
    plot_xlimit_max: null
    plot_xlimit_min: null
    plot_xscale: linear
    plot_xticks_distance: null
    plot_xticks_max: null
    plot_xticks_min: null
    plot_ylabel: Density
    plot_ylabel_pad: 2.0
    plot_ylimit_max: null
    plot_ylimit_min: null
    plot_yscale: linear
    plot_yticks_distance: null
    plot_yticks_max: null
    plot_yticks_min: null
    plot_zlabel: z
    plot_zlabel_pad: 2.0
    plot_zlimit_max: null
    plot_zlimit_min: null
    plot_zscale: linear
    plot_zticks_distance: null
    plot_zticks_max: null
    plot_zticks_min: null
    plotlegend: true
    plotlegend_bbox_to_anchor_x: null
    plotlegend_bbox_to_anchor_y: null
    plotlegend_border_axisPad: 0.0
    plotlegend_location: 2
    plotlegend_mode: null
    plotlegend_ncolumn: 1

  Subplot1:
    dataset0:
      graph_alpha: 0.65
      graph_type: histogram
      input_edata: 0
      input_xdata: 39
      input_ydata: 2
      input_zdata: 
      plot_legend: DJI Spark - Captured Data
      dataset_ylabel: Data Rate (kbps)
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25
    dataset1:
      graph_alpha: 0.65
      graph_type: line
      input_edata: 0
      input_xdata: 42
      input_ydata: 45
      input_zdata: 
      plot_legend: Expon. Model
      dataset_ylabel: Data Rate (kbps)
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25
    multipleyaxis: false
    plot_threed_azimdegree: -160
    plot_threed_elevdegree: 30
    plot_title: Downlink PDF Analysis
    plot_xlabel: Packet Inter-arrival (ms)
    plot_xlabel_pad: 2
    plot_xlimit_max: 41
    plot_xlimit_min: -5
    plot_xscale: linear
    plot_xticks_distance: 20
    plot_xticks_max: 41
    plot_xticks_min: 0
    plot_ylabel: Density
    plot_ylabel_pad: 2.0
    plot_ylimit_max: null
    plot_ylimit_min: null
    plot_yscale: linear
    plot_yticks_distance: null
    plot_yticks_max: null
    plot_yticks_min: null
    plot_zlabel: z
    plot_zlabel_pad: 2.0
    plot_zlimit_max: null
    plot_zlimit_min: null
    plot_zscale: linear
    plot_zticks_distance: null
    plot_zticks_max: null
    plot_zticks_min: null
    plotlegend: true
    plotlegend_bbox_to_anchor_x: null
    plotlegend_bbox_to_anchor_y: null
    plotlegend_border_axisPad: 0.0
    plotlegend_location: 2
    plotlegend_mode: null
    plotlegend_ncolumn: 1

  Subplot2:
    dataset0:
      graph_alpha: 0.65
      graph_type: histogram
      input_edata: 0
      input_xdata: 48
      input_ydata: 2
      input_zdata: 
      plot_legend: DJI Spark - Captured Data
      dataset_ylabel: Data Rate (kbps)
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25

    multipleyaxis: false
    plot_threed_azimdegree: -160
    plot_threed_elevdegree: 30
    plot_title: 
    plot_xlabel: Packet Length (bytes)
    plot_xlabel_pad: 2
    plot_xlimit_max: null
    plot_xlimit_min: null
    plot_xscale: linear
    plot_xticks_distance: null
    plot_xticks_max: null
    plot_xticks_min: null
    plot_ylabel: Density
    plot_ylabel_pad: 2.0
    plot_ylimit_max: null
    plot_ylimit_min: null
    plot_yscale: linear
    plot_yticks_distance: null
    plot_yticks_max: null
    plot_yticks_min: null
    plot_zlabel: z
    plot_zlabel_pad: 2.0
    plot_zlimit_max: null
    plot_zlimit_min: null
    plot_zscale: linear
    plot_zticks_distance: null
    plot_zticks_max: null
    plot_zticks_min: null
    plotlegend: true
    plotlegend_bbox_to_anchor_x: null
    plotlegend_bbox_to_anchor_y: null
    plotlegend_border_axisPad: 0.0
    plotlegend_location: 2
    plotlegend_mode: null
    plotlegend_ncolumn: 1

  Subplot3:
    dataset0:
      graph_alpha: 0.65
      graph_type: histogram
      input_edata: 0
      input_xdata: 0
      input_ydata: 2
      input_zdata: 
      plot_legend: DJI Spark - Captured Data
      dataset_ylabel: DJI Spark - Captured Data
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25

    multipleyaxis: false
    plot_threed_azimdegree: -160
    plot_threed_elevdegree: 30
    plot_title: 
    plot_xlabel: Data Rate (kbps)
    plot_xlabel_pad: 2
    plot_xlimit_max: null
    plot_xlimit_min: null
    plot_xscale: linear
    plot_xticks_distance: null
    plot_xticks_max: null
    plot_xticks_min: null
    plot_ylabel: Density
    plot_ylabel_pad: 2.0
    plot_ylimit_max: null
    plot_ylimit_min: null
    plot_yscale: linear
    plot_yticks_distance: null
    plot_yticks_max: null
    plot_yticks_min: null
    plot_zlabel: z
    plot_zlabel_pad: 2.0
    plot_zlimit_max: null
    plot_zlimit_min: null
    plot_zscale: linear
    plot_zticks_distance: null
    plot_zticks_max: null
    plot_zticks_min: null
    plotlegend: true
    plotlegend_bbox_to_anchor_x: null
    plotlegend_bbox_to_anchor_y: null
    plotlegend_border_axisPad: 0.0
    plotlegend_location: 2 
    plotlegend_mode: null
    plotlegend_ncolumn: 1

  Subplot4:
    dataset0:
      graph_alpha: 0.65
      graph_type: histogram
      input_edata: 0
      input_xdata: 9
      input_ydata: 2
      input_zdata: 
      plot_legend: DJI Spark - Captured Data 
      dataset_ylabel: Data Rate (kbps)
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25
    dataset1:
      graph_alpha: 0.65
      graph_type: line
      input_edata: 0
      input_xdata: 12
      input_ydata: 15
      input_zdata: 
      plot_legend: Expon. Model
      dataset_ylabel: Data Rate (kbps)
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25
    multipleyaxis: false
    plot_threed_azimdegree: -160
    plot_threed_elevdegree: 30
    plot_title: Uplink PDF Analysis
    plot_xlabel: Packet Inter-arrival (ms)
    plot_xlabel_pad: 2
    plot_xlimit_max: 31
    plot_xlimit_min: -5
    plot_xscale: linear
    plot_xticks_distance: 10
    plot_xticks_max: 31
    plot_xticks_min: 0
    plot_ylabel: Density
    plot_ylabel_pad: 2.0
    plot_ylimit_max: null
    plot_ylimit_min: null
    plot_yscale: linear
    plot_yticks_distance: null
    plot_yticks_max: null
    plot_yticks_min: null
    plot_zlabel: z
    plot_zlabel_pad: 2.0
    plot_zlimit_max: null
    plot_zlimit_min: null
    plot_zscale: linear
    plot_zticks_distance: null
    plot_zticks_max: null
    plot_zticks_min: null
    plotlegend: true
    plotlegend_bbox_to_anchor_x: null
    plotlegend_bbox_to_anchor_y: null
    plotlegend_border_axisPad: 0.0
    plotlegend_location: 2
    plotlegend_mode: null
    plotlegend_ncolumn: 1

  Subplot5:
    dataset0:
      graph_alpha: 0.65
      graph_type: histogram
      input_edata: 0
      input_xdata: 18
      input_ydata: 2
      input_zdata: 
      plot_legend: DJI Spark - Captured Data
      dataset_ylabel: Data Rate (kbps)
      yaxis_axisoffset: 0.1
      yaxis_on: true
      yaxis_ylimthreshold: 25

    multipleyaxis: false
    plot_threed_azimdegree: -160
    plot_threed_elevdegree: 30
    plot_title: 
    plot_xlabel: Packet Length (bytes)
    plot_xlabel_pad: 2
    plot_xlimit_max: null
    plot_xlimit_min: null
    plot_xscale: linear
    plot_xticks_distance: 500
    plot_xticks_max: 1501
    plot_xticks_min: 0
    plot_ylabel: Density
    plot_ylabel_pad: 2.0
    plot_ylimit_max: null
    plot_ylimit_min: null
    plot_yscale: linear
    plot_yticks_distance: null
    plot_yticks_max: null
    plot_yticks_min: null
    plot_zlabel: z
    plot_zlabel_pad: 2.0
    plot_zlimit_max: null
    plot_zlimit_min: null
    plot_zscale: linear
    plot_zticks_distance: null
    plot_zticks_max: null
    plot_zticks_min: null
    plotlegend: true
    plotlegend_bbox_to_anchor_x: null
    plotlegend_bbox_to_anchor_y: null
    plotlegend_border_axisPad: 0.0
    plotlegend_location: 2
    plotlegend_mode: null
    plotlegend_ncolumn: 1