
Subplot0:
  dataset0:
    HISTOGRAM:
      # Alignment of histogram bars. VALID inputs: {left, mid, right}. 
      align_histogram : 'left'
      # Number of bins in the graph
      binres : 0.5
      # Location of the bottom baseline of each bin. VALID inputs: array of scalar. 
      bottom : 0
      # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
      color : 0
      # Cumulative histogram 
      cumulative : false
      # Normalized probability density
      density : true 
      # Edge color of histogram bars # TBD, change it to numbers
      edgecolor : 'black'
      # Orientation of bins. VALID inputs: {horizontal, vertical}
      orientation : 'vertical' 
      # Relative width of the bars as a fraction of the bin width. VALID inputs: scalar or . 
      relativewidth :
      # Multiple data stacked on top of each other. 
      stacked : false
      # Type of histogram to draw. VALID inputs: {bar, barstacked, step, stepfilled}.  
      type : 'bar' 
Subplot1:
  dataset0:
    HISTOGRAM:
      # Alignment of histogram bars. VALID inputs: {left, mid, right}. 
      align_histogram : 'left'
      # Number of bins in the graph
      binres : 25
      # Location of the bottom baseline of each bin. VALID inputs: array of scalar. 
      bottom : 0
      # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
      color : 0
      # Cumulative histogram 
      cumulative : false
      # Normalized probability density
      density : true 
      # Edge color of histogram bars # TBD, change it to numbers
      edgecolor : 'black'
      # Orientation of bins. VALID inputs: {horizontal, vertical}
      orientation : 'vertical' 
      # Relative width of the bars as a fraction of the bin width. VALID inputs: scalar or . 
      relativewidth :
      # Multiple data stacked on top of each other. 
      stacked : false
      # Type of histogram to draw. VALID inputs: {bar, barstacked, step, stepfilled}.  
      type : 'bar'
Subplot2:
  dataset0:
    HISTOGRAM:
      # Alignment of histogram bars. VALID inputs: {left, mid, right}. 
      align_histogram : 'left'
      # Number of bins in the graph
      binres : 5
      # Location of the bottom baseline of each bin. VALID inputs: array of scalar. 
      bottom : 0
      # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
      color : 0
      # Cumulative histogram 
      cumulative : false
      # Normalized probability density
      density : true 
      # Edge color of histogram bars # TBD, change it to numbers
      edgecolor : 'black'
      # Orientation of bins. VALID inputs: {horizontal, vertical}
      orientation : 'vertical' 
      # Relative width of the bars as a fraction of the bin width. VALID inputs: scalar or . 
      relativewidth :
      # Multiple data stacked on top of each other. 
      stacked : false
      # Type of histogram to draw. VALID inputs: {bar, barstacked, step, stepfilled}.  
      type : 'bar'
Subplot3:
  dataset0:
    HISTOGRAM:
      # Alignment of histogram bars. VALID inputs: {left, mid, right}. 
      align_histogram : 'left'
      # Number of bins in the graph
      binres : 25
      # Location of the bottom baseline of each bin. VALID inputs: array of scalar. 
      bottom : 0
      # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
      color : 0
      # Cumulative histogram 
      cumulative : false
      # Normalized probability density
      density : true 
      # Edge color of histogram bars # TBD, change it to numbers
      edgecolor : 'black'
      # Orientation of bins. VALID inputs: {horizontal, vertical}
      orientation : 'vertical' 
      # Relative width of the bars as a fraction of the bin width. VALID inputs: scalar or . 
      relativewidth :
      # Multiple data stacked on top of each other. 
      stacked : false
      # Type of histogram to draw. VALID inputs: {bar, barstacked, step, stepfilled}.  
      type : 'bar' 
Subplot4:
  dataset0:
    HISTOGRAM:
      # Alignment of histogram bars. VALID inputs: {left, mid, right}. 
      align_histogram : 'left'
      # Number of bins in the graph
      binres : 25
      # Location of the bottom baseline of each bin. VALID inputs: array of scalar. 
      bottom : 0
      # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
      color : 0
      # Cumulative histogram 
      cumulative : false
      # Normalized probability density
      density : true 
      # Edge color of histogram bars # TBD, change it to numbers
      edgecolor : 'black'
      # Orientation of bins. VALID inputs: {horizontal, vertical}
      orientation : 'vertical' 
      # Relative width of the bars as a fraction of the bin width. VALID inputs: scalar or . 
      relativewidth :
      # Multiple data stacked on top of each other. 
      stacked : false
      # Type of histogram to draw. VALID inputs: {bar, barstacked, step, stepfilled}.  
      type : 'bar'
Subplot5:
  dataset0:
    HISTOGRAM:
      # Alignment of histogram bars. VALID inputs: {left, mid, right}. 
      align_histogram : 'left'
      # Number of bins in the graph
      binres : 100
      # Location of the bottom baseline of each bin. VALID inputs: array of scalar. 
      bottom : 0
      # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
      color : 0
      # Cumulative histogram 
      cumulative : false
      # Normalized probability density
      density : true 
      # Edge color of histogram bars # TBD, change it to numbers
      edgecolor : 'black'
      # Orientation of bins. VALID inputs: {horizontal, vertical}
      orientation : 'vertical' 
      # Relative width of the bars as a fraction of the bin width. VALID inputs: scalar or . 
      relativewidth :
      # Multiple data stacked on top of each other. 
      stacked : false
      # Type of histogram to draw. VALID inputs: {bar, barstacked, step, stepfilled}.  
      type : 'bar' 

##################################################
# ALL SETTINGS BELOW UNUSED
# JUST COPY/PASTE THE GRAPH TYPE AND ITS SETTINGS 
# FOR YOUR SUBPLOT&DATASET ABOVE
##################################################
BAR:
  ############ BAR PLOTS ############ - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.bar.html
  # alignments of bars to x-coordinates. Valid inputs: center, edge
  align_bar : 'center'
  # Valid inputs: array of scalar. Y coordinates of bars bases
  bottom : 0
  # Cap size of each bar. Can take it from config_matplotlibrc.py if set to 
  capsize : 0
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  color : 0 
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  edgecolor : 0 
  # Edge widths of bars. 0 means dont draw edges
  edgewidth : 1 
  # Labels of each bar. Set to  if you do not want labels
  label : 
  # Widths of the bars
  width : 1 
    
     

############ BOX PLOTS ############ - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.boxplot.html
BOX:
  # Number of times to bootstrap the median to determine its 95% confidence intervals. VALID inputs: int. 
  bootstrap : 
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  boxcolor : 4
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  capcolor : 0
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  fliercolor : 0
  # Labels of each box plot. Set to  if you do not want labels
  label : 
    - 'a'
    - 'b'
    - 'c'
    - 'd'
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  linecolor : 0
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  markeredgecolor : 0
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  mediancolor : 0
  # Produce notched box plots
  notched : false
  # Raw boxes with patch artists 
  patchartist : true
  # positions of each box 
  position : 
    - 1.5
    - 2.5
    - 3.5
    - 4.5
  # Produce vertical box plots
  vertical : true
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  whiskercolor : 0
  # The reach of whiskers beyond the 1st and 3rd quartiles
  whiskerreach : 1.5 
  # Widths of each box plot
  width : 0.5 
  # Sets the zorder of the boxplot. VALID inputs: scalar. 
  zorder : 

############ CDF ############ - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.plot.html
CDF:
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  color : 0 
  # Marker style. For acceptable inputs, check out https://matplotlib.org/api/markers_api.html#module-matplotlib.markers
  markerstyle : 'v' 
  # Marker size. 
  markersize : 15
  # Line style per plot. VALID inputs: {-, --, -., :, ,  , , solid, dashed, dashdot, dotted}
  style : 'solid'
  # Line width for lines per plots. First entry of array is the first input data. Increase array size if you plot more than 10 lines in a plot! 
  width : 10 

############ ERRORBAR ############ - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.errorbar.html
ERRORBAR:
  # Plot errorbars above the plot symbols
  barsabove : false
  # Cap size of errorbars. 
  capsize : 1 
  # Cap thickness of errorbars. 
  capthickness : 1
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  color : 0 
  # Linestyle per plot. Valid inputs: {-, --, -., :, ,  , , solid, dashed, dashdot, dotted}
  style : 'solid' 
  # Line width for lines per plots. First entry of array is the first input data. Increase array size if you plot more than 10 lines in a plot! 
  width : 1 

############ HISTOGRAM ############ - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.hist.html
HISTOGRAM:
  # Alignment of histogram bars. VALID inputs: {left, mid, right}. 
  align_histogram : 'left'
  # Number of bins in the graph
  binres : 1
  # Location of the bottom baseline of each bin. VALID inputs: array of scalar. 
  bottom : 0
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  color : 0
  # Cumulative histogram 
  cumulative : false
  # Normalized probability density
  density : true 
  # Edge color of histogram bars # TBD, change it to numbers
  edgecolor : 'black'
  # Orientation of bins. VALID inputs: {horizontal, vertical}
  orientation : 'vertical' 
  # Relative width of the bars as a fraction of the bin width. VALID inputs: scalar or . 
  relativewidth :
  # Multiple data stacked on top of each other. 
  stacked : false
  # Type of histogram to draw. VALID inputs: {bar, barstacked, step, stepfilled}.  
  type : 'bar' 

############ LINE ############ - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.plot.html
LINE:
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  color : 0 
  # Marker style. For acceptable inputs, check out https://matplotlib.org/api/markers_api.html#module-matplotlib.markers
  markerstyle : 'v'
  # Marker size. 
  markersize : 10
  # Line style per plot. Valid inputs: {-, --, -., :, ,  , , solid, dashed, dashdot, dotted}
  style : 'solid'
  # Line width for lines per plots. First entry of array is the first input data. Increase array size if you plot more than 10 lines in a plot! 
  width : 12

############ SEABORN JOINT ############ - https://seaborn.pydata.org/generated/seaborn.jointplot.html
SNSJOINT:
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  color : 0 
  # !!!ONLY ONE ENTRY!!! Type of graph for sns regression plots.  VALID inputs: {scatter, resid, reg, kde, hex}
  kind : 'reg' 

############ SEABORN LINE ############ - https://seaborn.pydata.org/generated/seaborn.lineplot.html https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.plot.html 
SNSLINE:
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  color : 0  
  # Grouping variable that will produce lines with different colors
  hue :
  # Marker style. For acceptable inputs, check out https://matplotlib.org/api/markers_api.html#module-matplotlib.markers
  markerstyle  : 'v' 
  # Marker size.
  markersize : 15 
  # Grouping variable that will produce lines with different widths
  size : 
  # Grouping variable that will produce lines with different dashes and/or markers
  sns_style :  
  # Linestyle per plot. VALID inputs: {-, --, -., :, ,  , , solid, dashed, dashdot, dotted}
  style : 'solid'
  # Line width for lines per plots. First entry of array is the first input data. Increase array size if you plot more than 10 lines in a plot! 
  width : 10 

############ 3D ############ - https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.plot.html
THREED:
  # Color order for lines per plot. 0: steelblue, 1: sandybrown, 2: mediumseagreen, 3: indianred, 4: dimgrey, 5: orchid, 6: goldenrod, 7: darkcyan, 8: mediumslateblue, 9: darkkhaki. ADD MORE COLOR CODES TO "self.colors:" in plotFuncs.py if you need more color options for your plot!
  color : 0
  # Marker style. For acceptable inputs, check out https://matplotlib.org/api/markers_api.html#module-matplotlib.markers
  markerstyle : 'v' 
  # Marker size. 
  markersize : 1
  # Linestyle per plot. Valid inputs: {-, --, -., :, ,  , , solid, dashed, dashdot, dotted}
  style : 'solid'
  # Line width for lines per plots. First entry of array is the first input data. Increase array size if you plot more than 10 lines in a plot! 
  width : 1